return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "biome",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "fish-lsp",
      "gitui",
      "gofumpt",
      "goimports",
      "gomodifytags",
      "gopls",
      "hadolint",
      "impl",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "protols",
      "shfmt",
      "sqls",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "tree-sitter-cli",
      "typos-lsp",
      "vtsls",
      "yaml-language-server",
    },
  },
}